import Mock from 'mockjs';


// 图表数据
let List = []
export default{
    getStatisticaData:()=>{
        // 通过MOck.Random.float 产生随机数100到8000之间 保留小数 最小0位 最大0位
        for(let i=0;i<7;i++){
            List.push(
                Mock.mock({
                    vivo:Mock.Random.float(100,8000,0,0),
                    苹果:Mock.Random.float(100,8000,0,0),
                    小米:Mock.Random.float(100,8000,0,0),
                    三星:Mock.Random.float(100,8000,0,0),
                    OPPO:Mock.Random.float(100,8000,0,0)
                })
            )
        }
        return {
            code:20000,
            data:{
                //饼图
                videData:[
                    {
                        name:'小米',
                        value:2999
                    },
                    {
                        name:'vivo',
                        value:3999
                    },
                    {
                        name:'苹果',
                        value:4999
                    },
                    {
                        name:'魅族',
                        value:5999
                    },
                    {
                        name:'OPPO',
                        value:2399
                    },
                    
                ],
                //柱状图
                userData:[
                    {
                        data:'周一',
                        new:5,
                        active:200
                    },
                    {
                        data:'周二',
                        new:10,
                        active:500
                    },
                    {
                        data:'周三',
                        new:12,
                        active:300
                    },
                    {
                        data:'周四',
                        new:60,
                        active:800
                    },
                    {
                        data:'周五',
                        new:65,
                        active:270
                    },
                    {
                        data:'周六',
                        new:53,
                        active:450
                    },
                    {
                        data:'周日',
                        new:53,
                        active:770
                    },
                ],
                //折线图
                orderData:{
                    date:['20220501','20220502','20220503','20220504','20220505','20220506','20220507'],
                    data:List
                },
                tableData:[
                    {
                        name:'vivo',
                        todayBuy:100,
                        monthBuy:300,
                        totalBuy:800,
                    },
                    {
                        name:'苹果',
                        todayBuy:100,
                        monthBuy:300,
                        totalBuy:800,
                    },
                    {
                        name:'小米',
                        todayBuy:100,
                        monthBuy:300,
                        totalBuy:800,
                    },
                    {
                        name:'三星',
                        todayBuy:100,
                        monthBuy:300,
                        totalBuy:800,
                    },
                    {
                        name:'OPPO',
                        todayBuy:100,
                        monthBuy:300,
                        totalBuy:800,
                    },
                ],
            }
        }
    }
}